spring.application.name=ufcpedia

server.port=8081

spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306:railway
spring.datasource.username=root
spring.datasource.password=XOKBJsxiIdzQwXiWNfRjOetrZlRjCkdt

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false