spring.application.name=ufcpedia

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/ufc
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false